baseurl = "/"
title = "Maxi's Blog"
theme = "papermod"

[Params]
    title = "Maxi's Blog"
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/MaxiG-ai"
    dateFormat = "Mon, Jan 2, 2006"
    keywords = ["blog", "dev", "triathlon"]

    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = false
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    UseHugoToc = true
    disableSpecial1stPost = false
    disableScrollToTop = false
    comments = false
    hidemeta = false
    hideSummary = false
    showtoc = false
    tocopen = false

[homeInfoParams]
    Title = "Maxi's Blog"
    Content = """
        👋 Welcome to my homepage on the internet!

        - Feel free to connect with me on any of the social platforms below.
        
        - Go to the [about](/about/) page to learn more about me.

        - Check out the [blog](/post/) for my latest posts.
        """
        
[[socialIcons]]
name = "github"
title = "Check out my GitHub"
url = "https://github.com/adityatelange/hugo-PaperMod"

[[socialIcons]]
name = "Discord"
title = "Join discord community"
url = "https://discord.gg/ahpmTvhVmp"


[Permalinks]
    post = "/:filename/"